config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "questions#index"
  resources :questions, :answers
  
  get 'follow_user', to: 'users#follow_user'
  get	'unfollow_user', to: 'users#unfollow_user'
	get 'follow_topic', to: 'users#follow_topic'
	get 'unfollow_topic', to: 'users#unfollow_topic'
end

app/models/answer.rb
class Answer < ApplicationRecord
	belongs_to :question
	belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :follower, foreign_key: 'user_id', class_name: 'User'
	belongs_to :following, foreign_key: 'following_id', class_name: 'User'
	validates :user_id, :uniqueness => {:scope => :following_id, message: 'User is already followed'} 
end

app/models/follow_topic.rb
class FollowTopic < ApplicationRecord
	belongs_to :user
	belongs_to :topic
end

app/models/question.rb
class Question < ApplicationRecord
	belongs_to :user
	belongs_to :topic
	has_many :answers
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :questions
	has_many :follows, as: :followable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  has_many :follows
  has_many :follower_relationship, foreign_key: :following_id, class_name: 'Follow'
  has_many :followers, through: :follower_relationship, source: :follower
  has_many :following_relationship, foreign_key: :user_id, class_name: 'Follow'
  has_many :following, through: :following_relationship, source: :following

 
  has_many :answers
  has_many :questions

  has_many :follow_topics
  has_many :topics, through: :follow_topics, source: :topic
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def create
  	@question = Question.find_by(id: answer_params[:question_id])
    @answer = @question.answers.create(answer_params)
    redirect_to question_path(@question)
  end

  private
  
  def answer_params
    params[:answer][:user_id] = current_user.id
    params.require(:answer).permit(:user_id, :description, :question_id, :answer_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :authenticate_user!

	def new
		@question = Question.new
		@topic = Topic.all
	end
	
	def index
		@questions = Question.all
	end

	def show
		@question = Question.find_by(id: params[:id])
		@answers = @question.answers
	end

	def create
		@question = current_user.questions.new(question_params)
		if @question.save
			redirect_to questions_path
		else
			redirect_to new_question_path
		end
	end

	private
	  def question_params
	    params.require(:question).permit(:name, :user_id, :topic_id)
	  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def follow_user
		current_user.follows.create(following_id: params[:user_id])
		redirect_to question_path(params[:question_id])
	end

	def unfollow_user
		follow = current_user.follows.find_by(following_id: params[:user_id])
		if follow.present?
			follow.destroy 
		end
		redirect_to question_path(params[:question_id])
	end

	def follow_topic
		current_user.follow_topics.create(topic_id: params[:topic_id])
		redirect_to question_path(params[:question_id])
	end

	def unfollow_topic
		follow_topic = current_user.follow_topics.find_by(topic_id: params[:topic_id])
		if follow_topic.present?
			follow_topic.destroy
		end
		redirect_to question_path(params[:question_id])
	end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
Hello! Welcome to Quora App

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoraDemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/shared/header" %>
    <%= render partial: "layouts/shared/flash_message"%>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_flash_message.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |type, msg| %>
      <% if type == "notice" %>
        <div class="alert alert-success">
      <% elsif type == "alert" %>
        <div class="alert alert-danger">
      <% else %>
        <div class='alert alert-<%= "#{type}" %>'>
      <% end %>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <ul>
        <li>
          <%= msg %>
        </li>
      </ul>
    <% end %>
  </div>
</div>

app/views/layouts/shared/_header.html.erb
<% if current_user.present? %>
	<%= link_to "logout", destroy_user_session_path(current_user), method: :delete%>
<% end %>

app/views/questions/index.html.erb
<h1>Listing Questions</h1>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Topic</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= link_to question.name, question_path(question), class: "question" %></td>
        <td><%= question.topic.description %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<%= link_to 'Add New Question', new_question_path %> 
<br>

app/views/questions/new.html.erb
 <%= form_with scope: :question, url: questions_path, local: true do |form| %>
  <p>
    <%= form.label :topic %><br>
    <%= form.select( "topic_id", Question.all.collect {|q| [q.name, q.id]}, { include_blank: true })  %>
  </p>
  
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<% unless current_user.follows.find_by(following_id: @question.user.id).present? %>
  <%= link_to "follow user", follow_user_path(user_id: @question.user.id, question_id: @question.id), class: "follow_user"%>
<% else %>
  <%= link_to "unfollow user", unfollow_user_path(user_id: @question.user.id, question_id: @question.id)%>
<% end %>
<span>: <%= @question&.user&.email  %> </span>
<br>
<% unless  current_user.follow_topics.find_by(topic_id: @question.topic.id).present? %>
  <%= link_to "follow topic", follow_topic_path(topic_id: @question.topic.id, question_id: @question.id), class: "follow_topic"%>
<% else %>
  <%= link_to "unfollow topic", unfollow_topic_path(topic_id: @question.topic.id, question_id: @question.id)%>
<% end %>
<span>: <%= @question&.topic&.description %></span>
<h1>Question Test</h1>

<p><%= @question.name %></p>

<h2>Answers to above question</h2>
<% @answers.each do |answer| %>
  <p class="answer"><%= answer.description %></p><br>
<% end %>

<%= form_with scope: :answer, url: answers_path, local: true do |form| %>
  <p>
    <%= form.label :answer %><br>
    <%= form.text_field :description %>
  </p>

  <%= hidden_field_tag "answer[question_id]", @question.id %>

  <p>
    <%= form.submit %>
  </p>

<% end %>

<%= link_to 'Back', questions_path %>
 